version: '3'

services:
  app:
    build: .
    container_name: app
    ports:
      - '8000:3000'
    volumes:
      - ./:/app

  browser:
    image: ghcr.io/browserless/chrome:latest
    container_name: browser
    restart: always
    ports:
      # For accessing the debugger
      - '8080:3000'
    environment:
      - CONCURRENT=10
      - TIMEOUT=60000
      - DATA_DIR=/tmp/my-profile

  # For later, once they figure out their self-hosting
  # inngest:
  #   image: inngest/inngest:latest
  #   container_name: inngest
  #   restart: always
  #   command: inngest serve runner executor event-api core-api
