# fly.toml app configuration file generated for newsman on 2023-12-12T08:11:56-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "newsman"
primary_region = "ewr"
swap_size_mb = 2048

[mounts]
source = "newsman_data"
destination = "/app/.auth"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
